const FETCH_CASES = 'FETCH_CASES';
const FETCH_CASES_SUCCESS = 'FETCH_CASES_SUCCESS';
const FETCH_CASES_FAILURE = 'FETCH_CASES_FAILURE';

export default {
  FETCH_CASES,
  FETCH_CASES_SUCCESS,
  FETCH_CASES_FAILURE
};
